CREATE DATABASE DB_CIDADE_DOS_VEGETAIS;
USE DB_CIDADE_DOS_VEGETAIS;
CREATE TABLE TB_CATEGORIAS(ID bigint(5) auto_increment, 
TIPO varchar(255) NOT NULL,
NOME varchar(255) NOT NULL,
primary key(ID));
CREATE TABLE TB_PRODUTOS(ID bigint(5) auto_increment,
QUANTIDADE int,
VALOR int,
ORGANICO boolean,
DELIVERY varchar(255),
CLASSE_ID bigint,
primary key(ID),
foreign key(CLASSE_ID) references TB_CATEGORIAS(ID));

INSERT INTO TB_CATEGORIAS (TIPO,NOME) values ("Vegetal","Alface");
INSERT INTO TB_CATEGORIAS (TIPO,NOME) values ("Vegetal","Rúcula");
INSERT INTO TB_CATEGORIAS (TIPO,NOME) values ("Raíz","Batata");
INSERT INTO TB_CATEGORIAS (TIPO,NOME) values ("Matinal","Cereal");
INSERT INTO TB_CATEGORIAS (TIPO,NOME) values ("Matinal","Sucrilhos");

SELECT* FROM TB_CATEGORIAS;

INSERT INTO TB_PRODUTOS (QUANTIDADE, VALOR, ORGANICO, DELIVERY, CLASSE_ID) values (88, 25, true, true, 1);
INSERT INTO TB_PRODUTOS (QUANTIDADE, VALOR, ORGANICO, DELIVERY, CLASSE_ID) values (126, 16, true, true, 2);
INSERT INTO TB_PRODUTOS (QUANTIDADE, VALOR, ORGANICO, DELIVERY, CLASSE_ID) values (45, 98, false, true, 3);
INSERT INTO TB_PRODUTOS (QUANTIDADE, VALOR, ORGANICO, DELIVERY, CLASSE_ID) values (60, 30, false, false, 4);
INSERT INTO TB_PRODUTOS (QUANTIDADE, VALOR, ORGANICO, DELIVERY, CLASSE_ID) values (35, 125, false, true, 5);
INSERT INTO TB_PRODUTOS (QUANTIDADE, VALOR, ORGANICO, DELIVERY, CLASSE_ID) values (56, 120, true, true, 4);
INSERT INTO TB_PRODUTOS (QUANTIDADE, VALOR, ORGANICO, DELIVERY, CLASSE_ID) values (61, 44, true, true, 5);
INSERT INTO TB_PRODUTOS (QUANTIDADE, VALOR, ORGANICO, DELIVERY, CLASSE_ID) values (97, 22, false, true, 4);

SELECT * FROM TB_PRODUTOS WHERE VALOR > 50;
SELECT * FROM TB_PRODUTOS WHERE VALOR > 50 AND VALOR <150;
SELECT * FROM TB_CATEGORIAS WHERE NOME LIKE "%C%";
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_PRODUTOS.CLASSE_ID=TB_CATEGORIAS.ID;
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_PRODUTOS.CLASSE_ID=TB_CATEGORIAS.ID WHERE TB_PRODUTOS.CLASSE_ID = 4;