CREATE DATABASE DB_PIZZARIA_LEGAL;
USE DB_PIZZARIA_LEGAL;
CREATE TABLE TB_CATEGORIAS(ID bigint(5) auto_increment, 
TIPO varchar(255) NOT NULL,
NOME varchar(255) NOT NULL,
primary key(ID));
CREATE TABLE TB_PIZZAS(ID bigint(5) auto_increment,
SABOR varchar(255),
VALOR int,
VEGETARIANA boolean,
ESPECIAL boolean,
CLASSE_ID bigint,
primary key(ID),
foreign key(CLASSE_ID) references TB_CATEGORIAS(ID));

INSERT INTO TB_CATEGORIAS (TIPO,NOME) values ("Salgado","Pizza");
INSERT INTO TB_CATEGORIAS (TIPO,NOME) values ("Salgado","Esfiha aberta");
INSERT INTO TB_CATEGORIAS (TIPO,NOME) values ("Salgado","Esfiha fechada");
INSERT INTO TB_CATEGORIAS (TIPO,NOME) values ("Doce","Pizza");
INSERT INTO TB_CATEGORIAS (TIPO,NOME) values ("Doce","Esfiha aberta");

SELECT* FROM TB_CATEGORIAS;

INSERT INTO TB_PIZZAS (SABOR, VALOR, VEGETARIANA, ESPECIAL, CLASSE_ID) values ("Portuguesa", 35, false, false, 1);
INSERT INTO TB_PIZZAS (SABOR, VALOR, VEGETARIANA, ESPECIAL, CLASSE_ID) values ("Quatro Queijos", 46, true, false, 1);
INSERT INTO TB_PIZZAS (SABOR, VALOR, VEGETARIANA, ESPECIAL, CLASSE_ID) values ("Estrogonoff", 62, false, true, 1);
INSERT INTO TB_PIZZAS (SABOR, VALOR, VEGETARIANA, ESPECIAL, CLASSE_ID) values ("Sensação", 35, true, false, 4);
INSERT INTO TB_PIZZAS (SABOR, VALOR, VEGETARIANA, ESPECIAL, CLASSE_ID) values ("Carne", 25, false, false, 2);
INSERT INTO TB_PIZZAS (SABOR, VALOR, VEGETARIANA, ESPECIAL, CLASSE_ID) values ("Queijo", 25, true, false, 3);
INSERT INTO TB_PIZZAS (SABOR, VALOR, VEGETARIANA, ESPECIAL, CLASSE_ID) values ("Chocolate com morango", 50, true, true, 4);
INSERT INTO TB_PIZZAS (SABOR, VALOR, VEGETARIANA, ESPECIAL, CLASSE_ID) values ("Doce de leite", 25, true, false, 5);

SELECT * FROM TB_PIZZAS WHERE VALOR > 45;
SELECT * FROM TB_PIZZAS WHERE VALOR > 50 AND VALOR <100;
SELECT * FROM TB_PIZZAS WHERE SABOR LIKE "%M%";
SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_PIZZAS.CLASSE_ID=TB_CATEGORIAS.ID;
SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_PIZZAS.CLASSE_ID=TB_CATEGORIAS.ID WHERE TB_PIZZAS.CLASSE_ID = 4;