CREATE DATABASE DB_GENERATION_GAME_ONLINE;
USE DB_GENERATION_GAME_ONLINE;
CREATE TABLE TB_CLASSES(ID bigint(5) auto_increment, 
TIPO varchar(255) NOT NULL,
NOME varchar(255) NOT NULL,
primary key(ID));
CREATE TABLE TB_PERSONAGENS(ID bigint(5) auto_increment,
NOME varchar(255),
IDADE int,
HABILIDADE varchar(255),
STAMINA int,
CLASSE_ID bigint,
primary key(ID),
foreign key(CLASSE_ID) references TB_CLASSES(ID));

INSERT INTO TB_CLASSES (TIPO,NOME) values ("Guerreiro","Knight");
INSERT INTO TB_CLASSES (TIPO,NOME) values ("Guerreiro","Barbarian");
INSERT INTO TB_CLASSES (TIPO,NOME) values ("Feiticeiro","Warlock");
INSERT INTO TB_CLASSES (TIPO,NOME) values ("Feiticeiro","Paladin");
INSERT INTO TB_CLASSES (TIPO,NOME) values ("Especial","Bard");

SELECT* FROM TB_CLASSES;

INSERT INTO TB_PERSONAGENS (NOME,IDADE,HABILIDADE,STAMINA,CLASSE_ID) values ("Aragorn",30, "Combate", 18, 1);
INSERT INTO TB_PERSONAGENS (NOME,IDADE,HABILIDADE,STAMINA,CLASSE_ID) values ("Beedle",52, "Cantar", 15, 5);
INSERT INTO TB_PERSONAGENS (NOME,IDADE,HABILIDADE,STAMINA,CLASSE_ID) values ("Boromir",28, "Combate", 20, 4);
INSERT INTO TB_PERSONAGENS (NOME,IDADE,HABILIDADE,STAMINA,CLASSE_ID) values ("Sauron",58, "Feitiços", 10, 3);
INSERT INTO TB_PERSONAGENS (NOME,IDADE,HABILIDADE,STAMINA,CLASSE_ID) values ("Orc",8, "Força", 6, 2);
INSERT INTO TB_PERSONAGENS (NOME,IDADE,HABILIDADE,STAMINA,CLASSE_ID) values ("Faramir",31, "Espadas", 16, 1);
INSERT INTO TB_PERSONAGENS (NOME,IDADE,HABILIDADE,STAMINA,CLASSE_ID) values ("Legolas",120, "Arco e flecha", 30, 1);
INSERT INTO TB_PERSONAGENS (NOME,IDADE,HABILIDADE,STAMINA,CLASSE_ID) values ("Gandalf",90, "Feitiços",14, 4);

SELECT * FROM TB_PERSONAGENS WHERE STAMINA > 20;
SELECT * FROM TB_PERSONAGENS WHERE STAMINA > 10 AND STAMINA <20;
SELECT * FROM TB_PERSONAGENS WHERE NOME LIKE "%C%";
SELECT * FROM TB_PERSONAGENS INNER JOIN TB_CLASSES ON TB_PERSONAGENS.CLASSE_ID=TB_CLASSES.ID;
SELECT * FROM TB_PERSONAGENS INNER JOIN TB_CLASSES ON TB_PERSONAGENS.CLASSE_ID=TB_CLASSES.ID WHERE TB_PERSONAGENS.CLASSE_ID = 3;